### PR TITLE
Time date split bootstrap

### PR DESCRIPTION
**Pull request by MichelSaremi**
Split Goal-dashboard into several child components, and added bootstrap styling

### CODE REVIEW

**Comment by livstella** [comment]
Seems the progress bar and time left might not be working

**Comment by Epiko1994** [comment]
> Seems the progress bar and time left might not be working

**Comment by Epiko1994** [comment]
> Seems the progress bar and time left might not be working

Det ser ud til at virke fint hos mig?

**Comment by livstella** [comment]
> > Seems the progress bar and time left might not be working
> 
> Det ser ud til at virke fint hos mig?

Cool. Så var det nok bare mig det var lidt for hurtig i mellem interviews

**Review by livstella — APPROVED** [review]

**Review by Epiko1994 — APPROVED** [review]

**Pull request merged**
